project:
  type: website 
  output-dir: docs

baseURL: http://lauraleechu.github.io
languageCode: en-us
theme: hugo-digital-garden-theme
params:
  description: Hi! I'm Laura :)
  initials: L
  name: Laura Lee-Chu
menu:
  main:
    - name: Projects
      url: /projects/
      weight: 2
    - name: Resume
      embed-pdf url: content/resume.pdf/
      weight: 3
    - name: About
      url: /about/
      weight: 1

# markup:
#   defaultMarkdownHandler: goldmark
#   goldmark:
#     extensions:
#       definitionList: yes
#       footnote: yes
#       linkify: yes
#       strikethrough: yes
#       table: yes
#       taskList: yes
#       typographer: yes
#     renderer:
#       unsafe: yes
  # highlight:
  #   style: monokailight
